### PR TITLE
Added missing Path parameter for teamwork schema

### LINKED ISSUE #70: PropertyNotFoundException: The property 'Path' cannot be found on this object.
PR #69 causes `PropertyNotFoundException` on lines 103, 108, 149, and 150.

This is caused by a missing Path attribute for the Teams object in [Get-EEDefaultSchema.ps1](https://github.com/microsoft/EntraExporter/blob/33c07f4750c641010534ccff659558272c2eb299/src/Get-EEDefaultSchema.ps1#L856).

This output occurs when using the `All`, `Config`, or `Teams` tags. 

```powershell
C:\Temp> Export-Entra -Type Teams -Path 'C:\Temp\EntraExporter\Teams'
PropertyNotFoundException: C:\Users\sturd\Repositories\Public\EntraExporter\src\Export-Entra.ps1:103
Line |
 103 |              $outputFileName = Join-Path -Path $Path -ChildPath $item. …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'Path' cannot be found on this object. Verify that the property exists.
PropertyNotFoundException: C:\Users\sturd\Repositories\Public\EntraExporter\src\Export-Entra.ps1:108
Line |
 108 |              Write-Host "$spacer $($item.Path)"
     |                                    ~~~~~~~~~~
     | The property 'Path' cannot be found on this object. Verify that the property exists.

Join-Path: C:\Users\sturd\Repositories\Public\EntraExporter\src\Export-Entra.ps1:149
Line |
 149 |  …         $itemOutputFileName = Join-Path -Path $outputFileName -ChildP …
     |                                                  ~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'Path' because it is null.
Join-Path: C:\Users\sturd\Repositories\Public\EntraExporter\src\Export-Entra.ps1:150
Line |
 150 |  …         $parentOutputFileName = Join-Path $itemOutputFileName -ChildP …
     |                                              ~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'Path' because it is null.
```

### PR DESCRIPTION
**Pull request by SamErde**
This fixes #70 that was introduced with #69. Feel free to adjust the path if something else would be more appropriate. For now, I aligned it with the path for the SharePoint output.

### CODE REVIEW

**Comment by milapointe** [comment]
@SamErde should the readme reflect all those changes in the exported configuration?

**Comment by SamErde** [comment]
> @SamErde should the readme reflect all those changes in the exported configuration?

Yes, but it might be helpful to wait for this PR to be merged and the bug fixed before advertising the changes. The information pulled doesn't contain much detail, so I'm curious if @ramical has any plans to loop back and add more for the components that he recently introduced.

**Comment by milapointe** [comment]
> > @SamErde should the readme reflect all those changes in the exported configuration?
> 
> Yes, but it might be helpful to wait for this PR to be merged and the bug fixed before advertising the changes. The information pulled doesn't contain much detail, so I'm curious if @ramical has any plans to loop back and add more for the components that he recently introduced.

Yes exactly my point 😅 thanks

**Review by merill — APPROVED** [review]
Thanks folks! Good catch.

**Pull request merged**
